### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by Unicorn254** [550975101/scf-demo-java#8]
作者大大，data_json 这段数组能单发一下吗，我复制过去貌似规则好像有点问题

**Comment by 550975101** [comment]
您的编辑器自己添加转义符了，先直接粘贴 完事 手动加”“双引号，先双引号 再复制就有这样的问题，有转义符其实也没事

**Comment by Unicorn254** [comment]
我试试，谢谢大大，不过这文件我data_json我单独放到了一个文件里面了
